[package]
name = "fcoinman"
version = "0.1.14"
edition = "2021"
description = "Linux server compromise detector — based on real XMRig + Kaiten IRC bot incident"
license = "MIT"
repository = "https://github.com/RainyForest23/fcoinman"
keywords = ["security", "linux", "cryptominer", "malware", "detection"]
categories = ["command-line-utilities"]

[[bin]]
name = "fcoinman"
path = "src/main.rs"

[dependencies]
clap       = { version = "4", features = ["derive"] }
serde      = { version = "1", features = ["derive"] }
serde_json = "1"
colored    = "2"
sha2       = "0.10"
hex        = "0.4"
chrono     = { version = "0.4", features = ["serde"] }

[profile.release]
strip   = true
opt-level = "z"
lto     = true
